### ISSUE TITLE
package.json has a test the returns 1 and causes build to fail

### ISSUE THREAD

**Issue by enenum** [googlecodelabs/workbox-lab#29]
Consequently, the service worker is not updated to cache css files in step 6. 
After making it return zero, the service worker was update.

**Comment by DavidScales** [comment]
Hi enenum, thanks for filing a bug. Could you be more specific about which test fails and how? I don't believe there are any tests in _package.json_, unless you mean the `test` npm script, which is not used in the lab.

**Comment by enenum** [comment]
I am not saying there is a 'real' test. I am saying there is a line that in the script that is perhaps shows how to invoke tests, and it has an exit code that causes the build to fail. 

```
{
  "name": "workbox-lab",
  "version": "1.0.0",
  "description": "a lab for learning workbox",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
```
See - it says && exit 1
That is the problem. Newbies using the tutorial may struggle plenty not knowing why things are not working. Change it to exit 0 - or remove the line all together - and you will be making so many more people smile.

**Comment by DavidScales** [comment]
Ah okay I think I see what you're saying now. However, this is the default configuration of _package.json_, and I think the behavior is actually intended, i.e, since there are no tests for the application, an error is thrown to let the developer know that they need to specify tests. I suppose otherwise you could falsely assume your tests are passing. 

I don't believe the tutorial utilizes the `test` script, so for your own purposes you might be better off changing it to fit your own use case and build process. Let me know if you have any more questions!
