### ISSUE TITLE
Error : That is not a valid source service worker file. Please try again with a file containing 'self.__WB_MANIFEST'.

### ISSUE THREAD

**Issue by 805bluebell** [googlecodelabs/workbox-lab#30]
I was following the tutorial [here ](https://codelabs.developers.google.com/codelabs/workbox-lab/index.html#4)& using workbox wizard with `workbox wizard --injectManifest`.

Prompt comes in & I fill everything. Then it asks 
> path to your source service worker
to which I enter `src/sw.js`.

But guess what it throw an error
```
C:\Users\pankaj.kum\Desktop\sandbox\workboz_trial\workbox-lab\project>workbox wizard --injectManifest
? What is the root of your web app (i.e. which directory do you deploy)? build/
? Which file types would you like to precache? (Press <space> to select, <a> to toggle all, <i> to invert selection)jpg,
 svg, html, js, css
? Where's your existing service worker file? To be used with injectManifest, it should include a call to 'self.__WB_MANI
FEST' src/sw.js

That is not a valid source service worker file. Please try again with a file containing 'self.__WB_MANIFEST'.
```
What am I missing here?

**Comment by DavidScales** [comment]
Hi 805bluebell, I think we'd need some more info to help you debug this issue. Do you have a service worker file at src/sw.js? 

If so, one thing that could be causing issues is a version mismatch. Workbox has since released new versions since the lab dependencies were specified. So perhaps the workbox-cli wizard version that you're installing does not match with the local workbox libraries that are installed?

**Comment by 805bluebell** [comment]
Yes,  have a service worker file at src/sw.js with the following inside:
```
import { precacheAndRoute } from "workbox-precaching";

precacheAndRoute(self.__WB_MANIFEST);

importScripts(
  "https://storage.googleapis.com/workbox-cdn/releases/3.5.0/workbox-sw.js"
);

if (workbox) {
  console.log("Workbox is loading");
} else {
  console.log(`Boo! Workbox didn't load`);
}
```

I have `workbox-cli@5.0.0` installed globally.
Also, my `packahe.json` looks like this:
```
{
  "name": "workbox-lab",
  "version": "1.0.0",
  "description": "a lab for learning workbox",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "copy": "copyfiles -u 1 src/**/**/* src/**/* src/* build",
    "build": "npm run copy",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.3",
    "npm-check-updates": "^4.0.1"
  },
  "devDependencies": {
    "copyfiles": "^1.2.0"
  }
}
```

**Comment by DavidScales** [comment]
Ah okay, so I think you do in fact have a version mismatch. 

The lab was written in Workbox v3, and expects v3 of the CLI tool. You're using the v3 library with the v5 CLI tool. Since the library's API has changed between versions (e.g., CLI tool expects `workbox.precaching.precacheAndRoute([])` instead of a call to `self.__WB_MANIFEST`) the file generation is failing. 

I don't have the time to update the lab to v5 right now, but for now the easiest solution is for you to use the v3 CLI tool:

```
# uninstall v5 workbox-cli
npm uninstall -g workbox-cli
# install v3
npm install --global workbox-cli@^3.0.0
```

I'll update the installation step in the lab for future users.

That should work for you! Let me know if you're still having issues.

**Comment by 805bluebell** [comment]
The problem was the versions. Thanks a lot !
Hope to see more magic in workbox ;)
